### PR TITLE
Fuzzy search for posts

### PR DESCRIPTION
**Pull request by Pranjal-R-Agrawal**
Implemented function in the MongoDB DAO to fetch posts from the databases by performing fuzzy search on titles.

### CODE REVIEW

**Review by YathusanK — CHANGES_REQUESTED** [review]
Database requires update for implemented method to work.

**Comment by Pranjal-R-Agrawal** [comment]
> Database requires update for implemented method to work.

Which database did you try it on? I believe it should work on the standard database.

The issue with the test database is that the old resetDatabase function dropped the table, hence also deleting the index completely instead of updating it (also fixed in this branch).

**Comment by YathusanK** [comment]
> > Database requires update for implemented method to work.
> 
> Which database did you try it on? I believe it should work on the standard database.
> 
> The issue with the test database is that the old resetDatabase function dropped the table, hence also deleting the index completely instead of updating it (also fixed in this branch).

I was trying to test using the the configurations from the main file.

**Comment by Pranjal-R-Agrawal** [comment]
> > > Database requires update for implemented method to work.
> 
> > 
> 
> > Which database did you try it on? I believe it should work on the standard database.
> 
> > 
> 
> > The issue with the test database is that the old resetDatabase function dropped the table, hence also deleting the index completely instead of updating it (also fixed in this branch).
> 
> 
> 
> I was trying to test using the the configurations from the main file.

I see. I'll look into it.

**Comment by Pranjal-R-Agrawal** [comment]
@YathusanK Hi, I checked the code and it seems to be working. Add the following line of code as the final line in the `main` function in `Main.java`

```Java
mongoDBDataAccessObject.getPostsByTitle("ttt").forEach(post -> System.out.println(post.getTitle()));
```

It prints out the title of all the posts (the same title is printed out multiple times but that is not an error, the databse just seems to have several duplicates).

Note, it may take some time for posts to become searchable after being created since they have to be added to the search index first, which may not happen instantly.

**Comment by YathusanK** [comment]
> @YathusanK Hi, I checked the code and it seems to be working. Add the following line of code as the final line in the `main` function in `Main.java`
> 
> ```java
> mongoDBDataAccessObject.getPostsByTitle("ttt").forEach(post -> System.out.println(post.getTitle()));
> ```
> 
> It prints out the title of all the posts (the same title is printed out multiple times but that is not an error, the databse just seems to have several duplicates).
> 
> Note, it may take some time for posts to become searchable after being created since they have to be added to the search index first, which may not happen instantly.

Yup it works 👍

**Review by YathusanK — APPROVED** [review]
Fuzzy search method for titles works functions well. Integration Segregation Principle is also adhered to by making a new interface for this function.

**Review by Tanmay-Shinde — APPROVED** [review]
Tried testing the changes as per your and Yathusan's discussion above, it does work for me as well. Also good decision importing the entire com.mongodb.client and java.util packages. I think it's good to merge.

**Pull request merged**
